### ISSUE TITLE
unable to print invoice

### ISSUE THREAD

**Issue by karthicbz** [dveldhoen/easyinvoice#105]
the print method is throwing a runtime error

```pdf.js:8 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Object.print (http://localhost:3000/static/js/bundle.js:119977:48)
    at init (http://localhost:3000/static/js/bundle.js:119762:64)
    at EasyInvoice.print (http://localhost:3000/static/js/bundle.js:36177:5)
    at handleInvoicePrint (http://localhost:3000/static/js/bundle.js:1517:57)

  | print | @ | pdf.js:8
-- | -- | -- | --
  | init | @ | init.js:151
  | print | @ | easyinvoice.js:114
  | handleInvoicePrint | @ | InvoiceModal.jsx:204
  | await in handleInvoicePrint (async) |   |  
  | callCallback | @ | react-dom.development.js:4164
  | invokeGuardedCallbackDev | @ | react-dom.development.js:4213
  | invokeGuardedCallback | @ | react-dom.development.js:4277
  | invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:4291
  | executeDispatch | @ | react-dom.development.js:9041
  | processDispatchQueueItemsInOrder | @ | react-dom.development.js:9073
  | processDispatchQueue | @ | react-dom.development.js:9086
  | dispatchEventsForPlugins | @ | react-dom.development.js:9097
  | (anonymous) | @ | react-dom.development.js:9288
  | batchedUpdates$1 | @ | react-dom.development.js:26140
  | batchedUpdates | @ | react-dom.development.js:3991
  | dispatchEventForPluginEventSystem | @ | react-dom.development.js:9287
  | dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay | @ | react-dom.development.js:6465
  | dispatchEvent | @ | react-dom.development.js:6457
  | dispatchDiscreteEvent```

**Comment by karthicbz** [comment]
Sorry i have included a filename as argument in print method that is the cause of the issue.
